//! Cross-implementation smoke tests for the [`grpc`] crate (preview, 0.9.x)
//! talking to a [`tonic`] server. The `grpc` crate does not yet expose a
//! server API, so the official pattern (see the gRPC-Rust quickstart) is to
//! pair a tonic server with a grpc client.
//!
//! - [`helloworld_tonic`] contains the prost/tonic server stubs.
//! - [`helloworld_grpc`] contains the protobuf-rust/grpc client stubs.
//!
//! The crate is disabled on Windows for now because the gRPC-Rust
//! `protoc-gen-rust-grpc` plugin's cmake-based bootstrap fails on the CI
//! runner.

#![cfg(not(windows))]

/// Server-side stubs generated by `tonic-prost-build`.
pub mod helloworld_tonic {
    tonic::include_proto!("helloworld");
}

/// Client-side stubs generated by `grpc-protobuf-build`. The build script
/// places them under `OUT_DIR/grpc_gen/`.
#[allow(unused_imports)] // generated `use grpc::client::*` in helloworld_grpc.pb.rs
pub mod helloworld_grpc {
    // Protobuf message types (protobuf-rust, not prost).
    include!(concat!(env!("OUT_DIR"), "/grpc_gen/generated.rs"));
    // gRPC client stubs (take a `grpc::client::Channel`).
    include!(concat!(env!("OUT_DIR"), "/grpc_gen/helloworld_grpc.pb.rs"));
}

/// Plaintext `helloworld.Greeter` server built on tonic.
pub mod server {
    use crate::helloworld_tonic::{
        HelloReply, HelloRequest,
        greeter_server::{Greeter, GreeterServer},
    };
    use tokio::net::TcpListener;
    use tonic::{
        Request, Response, Status,
        transport::{Server, server::TcpIncoming},
    };

    #[derive(Default)]
    pub struct MyGreeter {}

    #[tonic::async_trait]
    impl Greeter for MyGreeter {
        async fn say_hello(
            &self,
            request: Request<HelloRequest>,
        ) -> Result<Response<HelloReply>, Status> {
            println!("Got a request from {:?}", request.remote_addr());
            let reply = HelloReply {
                message: format!("Hello {}!", request.into_inner().name),
            };
            Ok(Response::new(reply))
        }
    }

    /// Runs the `GreeterServer` on a pre-bound `listener` until `shutdown`
    /// resolves. The caller can bind to port 0 and use
    /// `listener.local_addr()` to learn the OS-assigned port.
    pub async fn serve(
        listener: TcpListener,
        shutdown: impl std::future::Future<Output = ()> + Send + 'static,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        let incoming = TcpIncoming::from(listener);
        Server::builder()
            .add_service(GreeterServer::new(MyGreeter::default()))
            .serve_with_incoming_shutdown(incoming, shutdown)
            .await?;
        Ok(())
    }
}

/// `helloworld.Greeter` client built on the [`grpc`] crate (preview 0.9.x).
pub mod client {
    use crate::helloworld_grpc::HelloRequest;
    use crate::helloworld_grpc::greeter_client::GreeterClient;
    use grpc::client::{Channel, ChannelOptions};
    use grpc::credentials::LocalChannelCredentials;
    use protobuf::proto;
    use std::sync::Arc;

    /// Issues a single `SayHello(name)` to `target` (e.g. `"dns:///[::1]:50061"`)
    /// and returns the greeting string from the server.
    pub async fn say_hello(target: &str, name: &str) -> String {
        // LocalChannelCredentials is a safe plaintext credential type that
        // refuses to connect to non-local addresses.
        let channel = Channel::new(
            target,
            Arc::new(LocalChannelCredentials::new()),
            ChannelOptions::default(),
        );
        let client = GreeterClient::new(channel);

        let request = proto!(HelloRequest {
            name: name.to_owned(),
        });
        let response = client
            .say_hello(request.as_view())
            .await
            .expect("RPC error");
        response.message().to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::{client, server};

    /// In-process end-to-end test: spawns the tonic-based `GreeterServer` on
    /// a tokio task and drives it with a `grpc::client::Channel` client in
    /// the same process.
    #[tokio::test(flavor = "multi_thread")]
    async fn client_server_in_process() {
        // Bind to port 0 so the OS picks a free port; the client then
        // connects to the resulting `local_addr`.
        let listener = tokio::net::TcpListener::bind("127.0.0.1:0").await.unwrap();
        let addr = listener.local_addr().unwrap();
        println!("GreeterServer listening on {addr}");

        let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel::<()>();
        let server_handle = tokio::spawn(async move {
            server::serve(listener, async {
                let _ = shutdown_rx.await;
            })
            .await
            .expect("server error");
        });

        let target = format!("dns:///{addr}");
        let greeting = client::say_hello(&target, "Tonic").await;
        assert_eq!(greeting, "Hello Tonic!");

        let _ = shutdown_tx.send(());
        server_handle.await.expect("server task panicked");
    }
}
